[2024-10-02T17:28:16.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:16.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T17:28:16.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T17:28:16.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:16.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-12 00:00:00+00:00
[2024-10-02T17:28:16.726+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2060) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:16.730+0000] {standard_task_runner.py:63} INFO - Started process 2081 to run task
[2024-10-02T17:28:16.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpy_95nz79']
[2024-10-02T17:28:16.737+0000] {standard_task_runner.py:91} INFO - Job 289: Subtask transformar
[2024-10-02T17:28:16.811+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:28:16.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-10-02T17:28:16.971+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:28:17.014+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:28:17.015+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:28:17.040+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-12T00:00:00+00:00, execution_date=20240312T000000, start_date=20241002T172816, end_date=20241002T172817
[2024-10-02T17:28:17.057+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 289 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2081)
[2024-10-02T17:28:17.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:28:17.151+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:28:17.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:00:34.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:00:34.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T19:00:34.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T19:00:34.671+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:00:34.692+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-12 00:00:00+00:00
[2024-10-02T19:00:34.700+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6659) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:00:34.701+0000] {standard_task_runner.py:63} INFO - Started process 6676 to run task
[2024-10-02T19:00:34.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '1426', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpx5pa4wpn']
[2024-10-02T19:00:34.704+0000] {standard_task_runner.py:91} INFO - Job 1426: Subtask transformar
[2024-10-02T19:00:34.760+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:00:34.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-10-02T19:00:34.862+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:00:35.023+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:00:35.024+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:00:35.034+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-12T00:00:00+00:00, execution_date=20240312T000000, start_date=20241002T190034, end_date=20241002T190035
[2024-10-02T19:00:35.076+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:00:35.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:26:50.845+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:26:51.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T19:26:51.099+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-10-02T19:26:51.100+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:26:51.114+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-12 00:00:00+00:00
[2024-10-02T19:26:51.122+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:26:51.123+0000] {standard_task_runner.py:63} INFO - Started process 10112 to run task
[2024-10-02T19:26:51.123+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '2462', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmpanslj2mi']
[2024-10-02T19:26:51.125+0000] {standard_task_runner.py:91} INFO - Job 2462: Subtask transformar
[2024-10-02T19:26:51.171+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-12T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:26:51.258+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-10-02T19:26:51.259+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:26:51.442+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:26:51.443+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:26:51.453+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-12T00:00:00+00:00, execution_date=20240312T000000, start_date=20241002T192651, end_date=20241002T192651
[2024-10-02T19:26:51.501+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:26:51.526+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:26:51.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
