[2024-10-02T17:32:07.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:32:07.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T17:32:07.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T17:32:07.879+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:32:08.030+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-30 00:00:00+00:00
[2024-10-02T17:32:08.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:32:08.036+0000] {standard_task_runner.py:63} INFO - Started process 3240 to run task
[2024-10-02T17:32:08.037+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '667', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpghhjo08w']
[2024-10-02T17:32:08.038+0000] {standard_task_runner.py:91} INFO - Job 667: Subtask transformar
[2024-10-02T17:32:08.073+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:32:08.142+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-02T17:32:08.143+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:32:08.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:32:08.167+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:32:08.177+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241002T173207, end_date=20241002T173208
[2024-10-02T17:32:08.186+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 667 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 3240)
[2024-10-02T17:32:08.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:32:08.227+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:32:08.232+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:56:01.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:56:01.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T18:56:01.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T18:56:01.347+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:56:01.508+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-30 00:00:00+00:00
[2024-10-02T18:56:01.514+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5214) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:56:01.515+0000] {standard_task_runner.py:63} INFO - Started process 5222 to run task
[2024-10-02T18:56:01.515+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '963', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpsy_2vlvk']
[2024-10-02T18:56:01.518+0000] {standard_task_runner.py:91} INFO - Job 963: Subtask transformar
[2024-10-02T18:56:01.561+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:56:01.648+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-02T18:56:01.649+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:56:01.772+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:56:01.773+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:56:01.780+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241002T185601, end_date=20241002T185601
[2024-10-02T18:56:01.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:56:01.826+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:56:01.828+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:04:56.150+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:04:56.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T19:04:56.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-02T19:04:56.181+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:04:56.356+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-30 00:00:00+00:00
[2024-10-02T19:04:56.364+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8444) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:04:56.365+0000] {standard_task_runner.py:63} INFO - Started process 8451 to run task
[2024-10-02T19:04:56.365+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '2001', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpzm4i4kfv']
[2024-10-02T19:04:56.367+0000] {standard_task_runner.py:91} INFO - Job 2001: Subtask transformar
[2024-10-02T19:04:56.404+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:04:56.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-02T19:04:56.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:04:56.621+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:04:56.622+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:04:56.632+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241002T190456, end_date=20241002T190456
[2024-10-02T19:04:56.659+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:04:56.676+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:04:56.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
