[2024-10-02T17:31:44.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:31:44.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T17:31:44.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T17:31:44.186+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:31:44.370+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-11 00:00:00+00:00
[2024-10-02T17:31:44.378+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3132) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:31:44.379+0000] {standard_task_runner.py:63} INFO - Started process 3138 to run task
[2024-10-02T17:31:44.379+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfqp7uupl']
[2024-10-02T17:31:44.381+0000] {standard_task_runner.py:91} INFO - Job 633: Subtask transformar
[2024-10-02T17:31:44.419+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:31:44.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-10-02T17:31:44.498+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:31:44.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:31:44.526+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:31:44.538+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20241002T173144, end_date=20241002T173144
[2024-10-02T17:31:44.551+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 633 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 3138)
[2024-10-02T17:31:44.593+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:31:44.612+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:31:44.616+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:55:28.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:55:28.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T18:55:29.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T18:55:29.103+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:55:29.119+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-11 00:00:00+00:00
[2024-10-02T18:55:29.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4998) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:55:29.126+0000] {standard_task_runner.py:63} INFO - Started process 5017 to run task
[2024-10-02T18:55:29.126+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '895', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpoow6rrlm']
[2024-10-02T18:55:29.127+0000] {standard_task_runner.py:91} INFO - Job 895: Subtask transformar
[2024-10-02T18:55:29.164+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:55:29.251+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-10-02T18:55:29.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:55:29.392+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:55:29.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:55:29.400+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20241002T185528, end_date=20241002T185529
[2024-10-02T18:55:29.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:55:29.480+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:55:29.483+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:04:33.118+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:04:33.142+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T19:04:33.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-10-02T19:04:33.349+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:04:33.366+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-11 00:00:00+00:00
[2024-10-02T19:04:33.372+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8275) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:04:33.374+0000] {standard_task_runner.py:63} INFO - Started process 8294 to run task
[2024-10-02T19:04:33.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '1947', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp4ffmzbv1']
[2024-10-02T19:04:33.377+0000] {standard_task_runner.py:91} INFO - Job 1947: Subtask transformar
[2024-10-02T19:04:33.431+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-11T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:04:33.544+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-10-02T19:04:33.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:04:33.781+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:04:33.782+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:04:33.793+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20241002T190433, end_date=20241002T190433
[2024-10-02T19:04:33.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:04:33.899+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:04:33.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
