[2024-10-02T17:25:50.652+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:50.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T17:25:50.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T17:25:50.694+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:50.711+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-06 00:00:00+00:00
[2024-10-02T17:25:50.720+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1426) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:50.722+0000] {standard_task_runner.py:63} INFO - Started process 1432 to run task
[2024-10-02T17:25:50.722+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfyynxu2t']
[2024-10-02T17:25:50.724+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask transformar
[2024-10-02T17:25:50.975+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:51.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2024-10-02T17:25:51.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:51.184+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:51.185+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:25:51.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-06T00:00:00+00:00, execution_date=20231106T000000, start_date=20241002T172550, end_date=20241002T172551
[2024-10-02T17:25:51.209+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task transformar ('ContinentExp'; 1432)
[2024-10-02T17:25:51.257+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:25:51.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:51.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:51.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T18:57:51.943+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T18:57:51.944+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:51.967+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-06 00:00:00+00:00
[2024-10-02T18:57:51.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5601) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:51.977+0000] {standard_task_runner.py:63} INFO - Started process 5619 to run task
[2024-10-02T18:57:51.982+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '1086', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp9rerus3e']
[2024-10-02T18:57:51.985+0000] {standard_task_runner.py:91} INFO - Job 1086: Subtask transformar
[2024-10-02T18:57:52.067+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:52.192+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2024-10-02T18:57:52.197+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:52.455+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:52.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:52.475+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-06T00:00:00+00:00, execution_date=20231106T000000, start_date=20241002T185751, end_date=20241002T185752
[2024-10-02T18:57:52.519+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:52.547+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:57:52.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:24:09.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:24:09.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T19:24:09.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2024-10-02T19:24:09.364+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:24:09.382+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-06 00:00:00+00:00
[2024-10-02T19:24:09.390+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8975) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:24:09.392+0000] {standard_task_runner.py:63} INFO - Started process 8992 to run task
[2024-10-02T19:24:09.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '2094', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptowpv8dk']
[2024-10-02T19:24:09.396+0000] {standard_task_runner.py:91} INFO - Job 2094: Subtask transformar
[2024-10-02T19:24:09.477+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:24:09.629+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2024-10-02T19:24:09.632+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:24:09.735+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:24:09.736+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:24:09.747+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-06T00:00:00+00:00, execution_date=20231106T000000, start_date=20241002T192409, end_date=20241002T192409
[2024-10-02T19:24:09.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:24:09.839+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:24:09.844+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
