[2024-10-02T17:30:35.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:30:35.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T17:30:35.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T17:30:35.141+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:30:35.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-07-06 00:00:00+00:00
[2024-10-02T17:30:35.557+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2733) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:30:35.561+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-07-06T00:00:00+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpjp4abut1']
[2024-10-02T17:30:35.570+0000] {standard_task_runner.py:63} INFO - Started process 2750 to run task
[2024-10-02T17:30:35.572+0000] {standard_task_runner.py:91} INFO - Job 505: Subtask transformar
[2024-10-02T17:30:35.704+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:30:35.838+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T00:00:00+00:00'
[2024-10-02T17:30:35.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:30:35.893+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:30:35.894+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:30:35.914+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-07-06T00:00:00+00:00, execution_date=20240706T000000, start_date=20241002T173035, end_date=20241002T173035
[2024-10-02T17:30:35.930+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 505 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2750)
[2024-10-02T17:30:35.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:30:35.982+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:30:35.992+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:54:15.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:54:15.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T18:54:15.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T18:54:15.275+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:54:15.561+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-07-06 00:00:00+00:00
[2024-10-02T18:54:15.568+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4438) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:54:15.569+0000] {standard_task_runner.py:63} INFO - Started process 4454 to run task
[2024-10-02T18:54:15.569+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-07-06T00:00:00+00:00', '--job-id', '713', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpy46zp9c3']
[2024-10-02T18:54:15.571+0000] {standard_task_runner.py:91} INFO - Job 713: Subtask transformar
[2024-10-02T18:54:15.618+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:54:15.707+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T00:00:00+00:00'
[2024-10-02T18:54:15.709+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:54:15.843+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:54:15.844+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:54:15.853+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-07-06T00:00:00+00:00, execution_date=20240706T000000, start_date=20241002T185415, end_date=20241002T185415
[2024-10-02T18:54:15.903+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:54:15.913+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:03:14.389+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:03:14.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T19:03:14.764+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-10-02T19:03:14.765+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:03:14.791+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-07-06 00:00:00+00:00
[2024-10-02T19:03:14.800+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7692) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:03:14.803+0000] {standard_task_runner.py:63} INFO - Started process 7708 to run task
[2024-10-02T19:03:14.802+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-07-06T00:00:00+00:00', '--job-id', '1760', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpirxdzp6k']
[2024-10-02T19:03:14.811+0000] {standard_task_runner.py:91} INFO - Job 1760: Subtask transformar
[2024-10-02T19:03:14.888+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-07-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:03:15.016+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T00:00:00+00:00'
[2024-10-02T19:03:15.018+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:03:15.318+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:03:15.322+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:03:15.339+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-07-06T00:00:00+00:00, execution_date=20240706T000000, start_date=20241002T190314, end_date=20241002T190315
[2024-10-02T19:03:15.431+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:03:15.464+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:03:15.473+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
