[2024-10-02T17:28:36.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:36.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T17:28:36.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T17:28:36.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:36.237+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-04-04 00:00:00+00:00
[2024-10-02T17:28:36.241+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2189) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:36.242+0000] {standard_task_runner.py:63} INFO - Started process 2192 to run task
[2024-10-02T17:28:36.243+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-04-04T00:00:00+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpxl5ar24p']
[2024-10-02T17:28:36.244+0000] {standard_task_runner.py:91} INFO - Job 332: Subtask transformar
[2024-10-02T17:28:36.282+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:28:36.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-04T00:00:00+00:00'
[2024-10-02T17:28:36.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:28:36.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:28:36.374+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:28:36.383+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-04-04T00:00:00+00:00, execution_date=20240404T000000, start_date=20241002T172836, end_date=20241002T172836
[2024-10-02T17:28:36.393+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 332 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2192)
[2024-10-02T17:28:36.416+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:28:36.433+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:28:36.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:01:06.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:01:06.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T19:01:06.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T19:01:06.766+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:01:06.782+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-04-04 00:00:00+00:00
[2024-10-02T19:01:06.790+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6882) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:01:06.791+0000] {standard_task_runner.py:63} INFO - Started process 6897 to run task
[2024-10-02T19:01:06.791+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-04-04T00:00:00+00:00', '--job-id', '1496', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpretuaklp']
[2024-10-02T19:01:06.793+0000] {standard_task_runner.py:91} INFO - Job 1496: Subtask transformar
[2024-10-02T19:01:06.837+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:01:06.929+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-04T00:00:00+00:00'
[2024-10-02T19:01:06.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:01:07.097+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:01:07.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:01:07.108+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-04-04T00:00:00+00:00, execution_date=20240404T000000, start_date=20241002T190106, end_date=20241002T190107
[2024-10-02T19:01:07.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:01:07.186+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:01:07.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:27:19.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:27:19.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T19:27:19.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-10-02T19:27:19.612+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:27:19.678+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-04-04 00:00:00+00:00
[2024-10-02T19:27:19.688+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:27:19.692+0000] {standard_task_runner.py:63} INFO - Started process 10314 to run task
[2024-10-02T19:27:19.692+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-04-04T00:00:00+00:00', '--job-id', '2521', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmprudfsh0z']
[2024-10-02T19:27:19.695+0000] {standard_task_runner.py:91} INFO - Job 2521: Subtask transformar
[2024-10-02T19:27:19.769+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-04-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:27:19.925+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-04T00:00:00+00:00'
[2024-10-02T19:27:19.928+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:27:20.174+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:27:20.177+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:27:20.195+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-04-04T00:00:00+00:00, execution_date=20240404T000000, start_date=20241002T192719, end_date=20241002T192720
[2024-10-02T19:27:20.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:27:20.361+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:27:20.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
