[2024-10-02T17:27:04.909+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:27:04.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T17:27:04.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T17:27:04.937+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:27:05.084+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-19 00:00:00+00:00
[2024-10-02T17:27:05.089+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1792) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:27:05.091+0000] {standard_task_runner.py:63} INFO - Started process 1794 to run task
[2024-10-02T17:27:05.091+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpnhlo1mhv']
[2024-10-02T17:27:05.093+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask extrair
[2024-10-02T17:27:05.128+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:27:05.197+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-10-02T17:27:05.198+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:12.444+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:12.445+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:27:12.458+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-19T00:00:00+00:00, execution_date=20240119T000000, start_date=20241002T172704, end_date=20241002T172712
[2024-10-02T17:27:12.481+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1794)
[2024-10-02T17:27:12.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:12.540+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:12.545+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:06.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:06.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T18:59:06.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T18:59:06.526+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:06.549+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-19 00:00:00+00:00
[2024-10-02T18:59:06.560+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:06.562+0000] {standard_task_runner.py:63} INFO - Started process 6164 to run task
[2024-10-02T18:59:06.561+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '1264', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppzqkafgt']
[2024-10-02T18:59:06.563+0000] {standard_task_runner.py:91} INFO - Job 1264: Subtask extrair
[2024-10-02T18:59:06.613+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:06.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-10-02T18:59:06.744+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:13.214+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:13.215+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:13.237+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-19T00:00:00+00:00, execution_date=20240119T000000, start_date=20241002T185906, end_date=20241002T185913
[2024-10-02T18:59:13.294+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:13.324+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:59:13.329+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:37.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:37.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T19:25:37.830+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-10-02T19:25:37.830+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:37.915+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-19 00:00:00+00:00
[2024-10-02T19:25:37.922+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9610) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:37.923+0000] {standard_task_runner.py:63} INFO - Started process 9624 to run task
[2024-10-02T19:25:37.924+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '2301', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpuhm3k5d6']
[2024-10-02T19:25:37.926+0000] {standard_task_runner.py:91} INFO - Job 2301: Subtask extrair
[2024-10-02T19:25:38.233+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:38.359+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-10-02T19:25:38.361+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:45.150+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:45.151+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:45.168+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-19T00:00:00+00:00, execution_date=20240119T000000, start_date=20241002T192537, end_date=20241002T192545
[2024-10-02T19:25:45.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:45.289+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:45.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
