[2024-10-02T17:28:16.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:17.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T17:28:17.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T17:28:17.030+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:17.297+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-22 00:00:00+00:00
[2024-10-02T17:28:17.304+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2075) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:17.306+0000] {standard_task_runner.py:63} INFO - Started process 2089 to run task
[2024-10-02T17:28:17.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_b6ytgcb']
[2024-10-02T17:28:17.308+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask transformar
[2024-10-02T17:28:17.351+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:28:17.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-10-02T17:28:17.434+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:28:17.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:28:17.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:28:17.465+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-22T00:00:00+00:00, execution_date=20240322T000000, start_date=20241002T172817, end_date=20241002T172817
[2024-10-02T17:28:17.475+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 300 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2089)
[2024-10-02T17:28:17.520+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:28:17.540+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:28:17.543+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:00:51.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:00:51.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T19:00:51.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T19:00:51.319+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:00:51.338+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-22 00:00:00+00:00
[2024-10-02T19:00:51.348+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6760) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:00:51.351+0000] {standard_task_runner.py:63} INFO - Started process 6773 to run task
[2024-10-02T19:00:51.349+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '1456', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpt3go3r6s']
[2024-10-02T19:00:51.352+0000] {standard_task_runner.py:91} INFO - Job 1456: Subtask transformar
[2024-10-02T19:00:51.409+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:00:51.524+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-10-02T19:00:51.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:00:51.677+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:00:51.678+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:00:51.686+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-22T00:00:00+00:00, execution_date=20240322T000000, start_date=20241002T190051, end_date=20241002T190051
[2024-10-02T19:00:51.726+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:00:51.733+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:27:05.210+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:27:05.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T19:27:05.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-10-02T19:27:05.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:27:05.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-22 00:00:00+00:00
[2024-10-02T19:27:05.399+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10211) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:27:05.400+0000] {standard_task_runner.py:63} INFO - Started process 10215 to run task
[2024-10-02T19:27:05.400+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '2493', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmpug9pn3ax']
[2024-10-02T19:27:05.403+0000] {standard_task_runner.py:91} INFO - Job 2493: Subtask transformar
[2024-10-02T19:27:05.438+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-22T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:27:05.512+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-10-02T19:27:05.513+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:27:05.629+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:27:05.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:27:05.637+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-22T00:00:00+00:00, execution_date=20240322T000000, start_date=20241002T192705, end_date=20241002T192705
[2024-10-02T19:27:05.694+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:27:05.710+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:27:05.715+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
