[2024-10-02T17:28:59.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:59.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T17:28:59.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T17:28:59.781+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:59.953+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-05-07 00:00:00+00:00
[2024-10-02T17:28:59.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2325) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:59.961+0000] {standard_task_runner.py:63} INFO - Started process 2338 to run task
[2024-10-02T17:28:59.962+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-05-07T00:00:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfkowz79m']
[2024-10-02T17:28:59.963+0000] {standard_task_runner.py:91} INFO - Job 376: Subtask extrair
[2024-10-02T17:29:00.010+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:29:00.099+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-07T00:00:00+00:00'
[2024-10-02T17:29:00.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:29:11.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:29:11.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(2810975 bytes read, 1496327 more expected)
[2024-10-02T17:29:11.118+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-05-07T00:00:00+00:00, execution_date=20240507T000000, start_date=20241002T172859, end_date=20241002T172911
[2024-10-02T17:29:11.128+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 376 for task extrair (IncompleteRead(2810975 bytes read, 1496327 more expected); 2338)
[2024-10-02T17:29:11.148+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:29:11.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:01:38.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:01:38.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T19:01:38.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T19:01:38.737+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:01:38.749+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-05-07 00:00:00+00:00
[2024-10-02T19:01:38.753+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:01:38.754+0000] {standard_task_runner.py:63} INFO - Started process 7115 to run task
[2024-10-02T19:01:38.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-05-07T00:00:00+00:00', '--job-id', '1569', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpe3iiu477']
[2024-10-02T19:01:38.757+0000] {standard_task_runner.py:91} INFO - Job 1569: Subtask extrair
[2024-10-02T19:01:38.797+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:01:38.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-07T00:00:00+00:00'
[2024-10-02T19:01:38.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:01:44.445+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:01:44.446+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:01:44.460+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-05-07T00:00:00+00:00, execution_date=20240507T000000, start_date=20241002T190138, end_date=20241002T190144
[2024-10-02T19:01:44.678+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:01:44.708+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:01:44.715+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:27:46.610+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:27:46.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T19:27:46.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [queued]>
[2024-10-02T19:27:46.843+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:27:46.855+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-05-07 00:00:00+00:00
[2024-10-02T19:27:46.862+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10535) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:27:46.863+0000] {standard_task_runner.py:63} INFO - Started process 10547 to run task
[2024-10-02T19:27:46.863+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-05-07T00:00:00+00:00', '--job-id', '2601', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmpl67zbuv0']
[2024-10-02T19:27:46.865+0000] {standard_task_runner.py:91} INFO - Job 2601: Subtask extrair
[2024-10-02T19:27:46.910+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:27:47.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-07T00:00:00+00:00'
[2024-10-02T19:27:47.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:27:54.487+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:27:54.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:27:54.495+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-05-07T00:00:00+00:00, execution_date=20240507T000000, start_date=20241002T192746, end_date=20241002T192754
[2024-10-02T19:27:54.552+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:27:54.577+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:27:54.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
