[2024-10-02T17:32:02.736+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:32:02.764+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T17:32:02.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T17:32:02.776+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:32:03.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-17 00:00:00+00:00
[2024-10-02T17:32:03.044+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3198) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:32:03.046+0000] {standard_task_runner.py:63} INFO - Started process 3212 to run task
[2024-10-02T17:32:03.047+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp9usueh0a']
[2024-10-02T17:32:03.050+0000] {standard_task_runner.py:91} INFO - Job 653: Subtask transformar
[2024-10-02T17:32:03.107+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:32:03.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-10-02T17:32:03.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:32:03.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:32:03.263+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:32:03.280+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20241002T173202, end_date=20241002T173203
[2024-10-02T17:32:03.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 653 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 3212)
[2024-10-02T17:32:03.342+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:32:03.351+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:55:43.246+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:55:43.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T18:55:43.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T18:55:43.285+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:55:43.515+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-17 00:00:00+00:00
[2024-10-02T18:55:43.522+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5097) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:55:43.523+0000] {standard_task_runner.py:63} INFO - Started process 5108 to run task
[2024-10-02T18:55:43.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '926', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3ib7kbk9']
[2024-10-02T18:55:43.525+0000] {standard_task_runner.py:91} INFO - Job 926: Subtask transformar
[2024-10-02T18:55:43.573+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:55:43.674+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-10-02T18:55:43.675+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:55:43.830+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:55:43.831+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:55:43.840+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20241002T185543, end_date=20241002T185543
[2024-10-02T18:55:43.898+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:55:43.917+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:55:43.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:04:41.854+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:04:42.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T19:04:42.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-10-02T19:04:42.075+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:04:42.088+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-17 00:00:00+00:00
[2024-10-02T19:04:42.094+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:04:42.096+0000] {standard_task_runner.py:63} INFO - Started process 8352 to run task
[2024-10-02T19:04:42.095+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '1968', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbcj948i7']
[2024-10-02T19:04:42.098+0000] {standard_task_runner.py:91} INFO - Job 1968: Subtask transformar
[2024-10-02T19:04:42.139+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-17T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:04:42.232+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-10-02T19:04:42.234+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:04:42.386+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:04:42.386+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:04:42.394+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20241002T190442, end_date=20241002T190442
[2024-10-02T19:04:42.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:04:42.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
