[2024-10-02T17:27:08.272+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:27:08.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T17:27:08.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T17:27:08.323+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:27:08.531+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-30 00:00:00+00:00
[2024-10-02T17:27:08.537+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:27:08.539+0000] {standard_task_runner.py:63} INFO - Started process 1834 to run task
[2024-10-02T17:27:08.539+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp51n74m2r']
[2024-10-02T17:27:08.541+0000] {standard_task_runner.py:91} INFO - Job 217: Subtask extrair
[2024-10-02T17:27:08.589+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:27:08.701+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-10-02T17:27:08.702+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:14.420+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:14.421+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:27:14.433+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-30T00:00:00+00:00, execution_date=20240130T000000, start_date=20241002T172708, end_date=20241002T172714
[2024-10-02T17:27:14.447+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 217 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1834)
[2024-10-02T17:27:14.486+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:14.505+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:14.508+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:32.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:32.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T18:59:32.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T18:59:32.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:32.752+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-30 00:00:00+00:00
[2024-10-02T18:59:32.758+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:32.760+0000] {standard_task_runner.py:63} INFO - Started process 6321 to run task
[2024-10-02T18:59:32.759+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '1314', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptf5c0fwy']
[2024-10-02T18:59:32.761+0000] {standard_task_runner.py:91} INFO - Job 1314: Subtask extrair
[2024-10-02T18:59:32.801+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:32.882+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-10-02T18:59:32.885+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:39.764+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:39.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:39.780+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-30T00:00:00+00:00, execution_date=20240130T000000, start_date=20241002T185932, end_date=20241002T185939
[2024-10-02T18:59:39.873+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:39.886+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:39.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:39.777+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T19:25:39.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-10-02T19:25:39.961+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:39.972+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-30 00:00:00+00:00
[2024-10-02T19:25:39.978+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9641) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:39.979+0000] {standard_task_runner.py:63} INFO - Started process 9652 to run task
[2024-10-02T19:25:39.979+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '2312', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpmigyk0wh']
[2024-10-02T19:25:39.981+0000] {standard_task_runner.py:91} INFO - Job 2312: Subtask extrair
[2024-10-02T19:25:40.019+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:40.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-10-02T19:25:40.105+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:45.678+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:45.680+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:45.692+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-30T00:00:00+00:00, execution_date=20240130T000000, start_date=20241002T192539, end_date=20241002T192545
[2024-10-02T19:25:45.887+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:45.919+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:45.924+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
