[2024-10-02T17:28:16.352+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:16.385+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T17:28:16.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T17:28:16.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:16.727+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-19 00:00:00+00:00
[2024-10-02T17:28:16.737+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2062) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:16.739+0000] {standard_task_runner.py:63} INFO - Started process 2084 to run task
[2024-10-02T17:28:16.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpji5_p2jr']
[2024-10-02T17:28:16.742+0000] {standard_task_runner.py:91} INFO - Job 294: Subtask transformar
[2024-10-02T17:28:16.810+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:28:16.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-10-02T17:28:16.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:28:17.021+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:28:17.022+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:28:17.044+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-19T00:00:00+00:00, execution_date=20240319T000000, start_date=20241002T172816, end_date=20241002T172817
[2024-10-02T17:28:17.060+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 294 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2084)
[2024-10-02T17:28:17.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:28:17.149+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:28:17.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:00:51.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:00:51.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T19:00:51.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T19:00:51.745+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:00:51.756+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-19 00:00:00+00:00
[2024-10-02T19:00:51.763+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6763) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:00:51.765+0000] {standard_task_runner.py:63} INFO - Started process 6775 to run task
[2024-10-02T19:00:51.765+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '1458', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgwh2la2n']
[2024-10-02T19:00:51.767+0000] {standard_task_runner.py:91} INFO - Job 1458: Subtask transformar
[2024-10-02T19:00:51.814+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:00:51.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-10-02T19:00:51.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:00:52.164+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:00:52.165+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:00:52.181+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-19T00:00:00+00:00, execution_date=20240319T000000, start_date=20241002T190051, end_date=20241002T190052
[2024-10-02T19:00:52.220+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:00:52.235+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:26:54.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:26:54.591+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T19:26:54.600+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-10-02T19:26:54.601+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:26:54.619+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-03-19 00:00:00+00:00
[2024-10-02T19:26:54.630+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:26:54.632+0000] {standard_task_runner.py:63} INFO - Started process 10165 to run task
[2024-10-02T19:26:54.632+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '2475', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmpz1jqwvsp']
[2024-10-02T19:26:54.635+0000] {standard_task_runner.py:91} INFO - Job 2475: Subtask transformar
[2024-10-02T19:26:54.702+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-03-19T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:26:54.814+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-10-02T19:26:54.815+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:26:54.950+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:26:54.950+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:26:54.960+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-03-19T00:00:00+00:00, execution_date=20240319T000000, start_date=20241002T192654, end_date=20241002T192654
[2024-10-02T19:26:55.009+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:26:55.039+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:26:55.042+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
