[2024-10-02T17:30:19.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:30:20.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T17:30:20.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T17:30:20.023+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:30:20.192+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-06-29 00:00:00+00:00
[2024-10-02T17:30:20.197+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:30:20.198+0000] {standard_task_runner.py:63} INFO - Started process 2678 to run task
[2024-10-02T17:30:20.198+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '487', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpkgmgo69z']
[2024-10-02T17:30:20.200+0000] {standard_task_runner.py:91} INFO - Job 487: Subtask transformar
[2024-10-02T17:30:20.237+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:30:20.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-10-02T17:30:20.315+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:30:20.342+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:30:20.343+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:30:20.353+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20241002T173020, end_date=20241002T173020
[2024-10-02T17:30:20.363+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 487 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 2678)
[2024-10-02T17:30:20.411+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:30:20.430+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:30:20.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:54:12.343+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:54:12.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T18:54:12.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T18:54:12.394+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:54:12.762+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-06-29 00:00:00+00:00
[2024-10-02T18:54:12.770+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:54:12.772+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '692', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpf01rqyr1']
[2024-10-02T18:54:12.776+0000] {standard_task_runner.py:63} INFO - Started process 4403 to run task
[2024-10-02T18:54:12.777+0000] {standard_task_runner.py:91} INFO - Job 692: Subtask transformar
[2024-10-02T18:54:12.877+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:54:12.990+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-10-02T18:54:12.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:54:13.151+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:54:13.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:54:13.167+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20241002T185412, end_date=20241002T185413
[2024-10-02T18:54:13.241+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:54:13.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:02:50.833+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:02:51.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T19:02:51.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-10-02T19:02:51.246+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:02:51.274+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-06-29 00:00:00+00:00
[2024-10-02T19:02:51.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7558) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:02:51.289+0000] {standard_task_runner.py:63} INFO - Started process 7582 to run task
[2024-10-02T19:02:51.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '1714', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpornfqjkl']
[2024-10-02T19:02:51.293+0000] {standard_task_runner.py:91} INFO - Job 1714: Subtask transformar
[2024-10-02T19:02:51.378+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-06-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:02:51.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-10-02T19:02:51.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:02:51.777+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:02:51.778+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:02:51.791+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20241002T190251, end_date=20241002T190251
[2024-10-02T19:02:51.873+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:02:51.895+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:02:51.899+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
